### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by niccoloveltri** [nmvdw/GrpdHITs#1]
- [x] Additional examples
- [x] Limits of algebras in 1-types (terminal, products, inserters, equifiers)
- [x] Free algebra. (Conclusion: every HIT signature gives rise to a pseudomonad (a la Lack))
- [ ] Colimits of algebras in 1-types (initial, coproducts, co-inserters, and coequifiers). 
- [x] I'd like to also try something with the isomorphism theorems. I dunno how that will go.
- [ ] Expand some explanations and definitions in the paper to make it clearer.
